#include "settings.hpp"

Setting settings[NUMBER_OF_SETTINGS];

void initSettings() {
    settings[SETTING_ACQUISITION_DELAY] = {
        SETTING_NAME_ACQUISITION_DELAY,
        SETTING_DEFAULT_ACQUISITION_DELAY,
        SETTING_DEFAULT_ACQUISITION_DELAY,
        SETTING_ACQUISITION_DELAY_MIN,
        SETTING_ACQUISITION_DELAY_MAX
    };
    settings[SETTING_FILE_MAX_SIZE] = {
        SETTING_NAME_FILE_MAX_SIZE,
        SETTING_DEFAULT_FILE_MAX_SIZE,
        SETTING_DEFAULT_FILE_MAX_SIZE,
        SETTING_FILE_MAX_SIZE_MIN,
        SETTING_FILE_MAX_SIZE_MAX
    };
    settings[SETTING_ACQUISITION_TIMEOUT] = {
        SETTING_NAME_ACQUISITION_TIMEOUT,
        SETTING_DEFAULT_ACQUISITION_TIMEOUT,
        SETTING_DEFAULT_ACQUISITION_TIMEOUT,
        SETTING_ACQUISITION_TIMEOUT_MIN,
        SETTING_ACQUISITION_TIMEOUT_MAX
    };
    settings[SETTING_BRIGHTNESS_ENABLED] = {
        SETTING_NAME_BRIGHTNESS_ENABLED,
        SETTING_DEFAULT_BRIGHTNESS_ENABLED,
        SETTING_DEFAULT_BRIGHTNESS_ENABLED,
        SETTING_BRIGHTNESS_ENABLED_MIN,
        SETTING_BRIGHTNESS_ENABLED_MAX
    };
    settings[SETTING_BRIGHTNESS_LOW] = {
        SETTING_NAME_BRIGHTNESS_LOW,
        SETTING_DEFAULT_BRIGHTNESS_LOW,
        SETTING_DEFAULT_BRIGHTNESS_LOW,
        SETTING_BRIGHTNESS_LOW_MIN,
        SETTING_BRIGHTNESS_LOW_MAX
    };
    settings[SETTING_BRIGHTNESS_HIGH] = {
        SETTING_NAME_BRIGHTNESS_HIGH,
        SETTING_DEFAULT_BRIGHTNESS_HIGH,
        SETTING_DEFAULT_BRIGHTNESS_HIGH,
        SETTING_BRIGHTNESS_HIGH_MIN,
        SETTING_BRIGHTNESS_HIGH_MAX
    };
    settings[SETTING_TEMPERATURE_ENABLED] = {
        SETTING_NAME_TEMPERATURE_ENABLED,
        SETTING_DEFAULT_TEMPERATURE_ENABLED,
        SETTING_DEFAULT_TEMPERATURE_ENABLED,
        SETTING_TEMPERATURE_ENABLED_MIN,
        SETTING_TEMPERATURE_ENABLED_MAX
    };
    settings[SETTING_TEMPERATURE_MIN] = {
        SETTING_NAME_TEMPERATURE_MIN,
        SETTING_DEFAULT_TEMPERATURE_MIN,
        SETTING_DEFAULT_TEMPERATURE_MIN,
        SETTING_TEMPERATURE_MIN_MIN,
        SETTING_TEMPERATURE_MIN_MAX
    };
    settings[SETTING_TEMPERATURE_MAX] = {
        SETTING_NAME_TEMPERATURE_MAX,
        SETTING_DEFAULT_TEMPERATURE_MAX,
        SETTING_DEFAULT_TEMPERATURE_MAX,
        SETTING_TEMPERATURE_MAX_MIN,
        SETTING_TEMPERATURE_MAX_MAX
    };
    settings[SETTING_HUMIDITY_ENABLED] = {
        SETTING_NAME_HUMIDITY_ENABLED,
        SETTING_DEFAULT_HUMIDITY_ENABLED,
        SETTING_DEFAULT_HUMIDITY_ENABLED,
        SETTING_HUMIDITY_ENABLED_MIN,
        SETTING_HUMIDITY_ENABLED_MAX
    };
    settings[SETTING_HUMIDITY_MIN] = {
        SETTING_NAME_HUMIDITY_MIN,
        SETTING_DEFAULT_HUMIDITY_MIN,
        SETTING_DEFAULT_HUMIDITY_MIN,
        SETTING_HUMIDITY_MIN_MIN,
        SETTING_HUMIDITY_MIN_MAX
    };
    settings[SETTING_HUMIDITY_MAX] = {
        SETTING_NAME_HUMIDITY_MAX,
        SETTING_DEFAULT_HUMIDITY_MAX,
        SETTING_DEFAULT_HUMIDITY_MAX,
        SETTING_HUMIDITY_MAX_MIN,
        SETTING_HUMIDITY_MAX_MAX
    };
    settings[SETTING_PRESSURE_ENABLED] = {
        SETTING_NAME_PRESSURE_ENABLED,
        SETTING_DEFAULT_PRESSURE_ENABLED,
        SETTING_DEFAULT_PRESSURE_ENABLED,
        SETTING_PRESSURE_ENABLED_MIN,
        SETTING_PRESSURE_ENABLED_MAX
    };
    settings[SETTING_PRESSURE_MIN] = {
        SETTING_NAME_PRESSURE_MIN,
        SETTING_DEFAULT_PRESSURE_MIN,
        SETTING_DEFAULT_PRESSURE_MIN,
        SETTING_PRESSURE_MIN_MIN,
        SETTING_PRESSURE_MIN_MAX
    };
    settings[SETTING_PRESSURE_MAX] = {
        SETTING_NAME_PRESSURE_MAX,
        SETTING_DEFAULT_PRESSURE_MAX,
        SETTING_DEFAULT_PRESSURE_MAX,
        SETTING_PRESSURE_MAX_MIN,
    };
#if INTERPRETER
    settings[SETTING_BRIGHTNESS_ECONOMY_ENABLED] = {
        SETTING_NAME_BRIGHTNESS_ECONOMY_ENABLED,
        SETTING_DEFAULT_BRIGHTNESS_ECONOMY_ENABLED,
        SETTING_DEFAULT_BRIGHTNESS_ECONOMY_ENABLED,
        SETTING_BRIGHTNESS_ECONOMY_ENABLED_MIN,
        SETTING_BRIGHTNESS_ECONOMY_ENABLED_MAX
    };
    settings[SETTING_TEMPERATURE_ECONOMY_ENABLED] = {
        SETTING_NAME_TEMPERATURE_ECONOMY_ENABLED,
        SETTING_DEFAULT_TEMPERATURE_ECONOMY_ENABLED,
        SETTING_DEFAULT_TEMPERATURE_ECONOMY_ENABLED,
        SETTING_TEMPERATURE_ECONOMY_ENABLED_MIN,
        SETTING_TEMPERATURE_ECONOMY_ENABLED_MAX
    };
    settings[SETTING_HUMIDITY_ECONOMY_ENABLED] = {
        SETTING_NAME_HUMIDITY_ECONOMY_ENABLED,
        SETTING_DEFAULT_HUMIDITY_ECONOMY_ENABLED,
        SETTING_DEFAULT_HUMIDITY_ECONOMY_ENABLED,
        SETTING_HUMIDITY_ECONOMY_ENABLED_MIN,
        SETTING_HUMIDITY_ECONOMY_ENABLED_MAX
    };
    settings[SETTING_PRESSURE_ECONOMY_ENABLED] = {
        SETTING_NAME_PRESSURE_ECONOMY_ENABLED,
        SETTING_DEFAULT_PRESSURE_ECONOMY_ENABLED,
        SETTING_DEFAULT_PRESSURE_ECONOMY_ENABLED,
        SETTING_PRESSURE_ECONOMY_ENABLED_MIN,
        SETTING_PRESSURE_ECONOMY_ENABLED_MAX
    };
#endif
    for (int i = 0; i < NUMBER_OF_SETTINGS; i++) {
        settings[i].sum = 0;

        char name[MAX_SETTING_LENGTH] = "";
        strcpy_P(name, settings[i].name);
        for (int j = 0; j < strlen(name); j++) {
            settings[i].sum += name[j];
        }
    }
}
#if SETTINGS_IN_EEPROM
void updateSettingsFromEEPROM() {
    int value;
    for (int i = 0; i < NUMBER_OF_SETTINGS; i++) {
        EEPROM.get(i, value);
        if (!value) {
            EEPROM.put(i, settings[i].defaultValue);
            settings[i].value = settings[i].defaultValue;
        }
        else settings[i].value = value;
    }
}
#endif
void resetSettings() {
    for (int i = 0; i < NUMBER_OF_SETTINGS; i++) {
#if SETTINGS_IN_EEPROM
        EEPROM.put(i, settings[i].defaultValue);
#endif
        settings[i].value = settings[i].defaultValue;
    }
}

void setSetting(int id, long value) {
#if SETTINGS_IN_EEPROM
    EEPROM.put(id, value);
#endif
    settings[id].value = value;
}